{
  try {
    task.run();
  }
 catch (  Throwable e) {
    logger.severe(getName() + " caught an exception while processing task:" + task,e);
  }
}
