{
  try {
    final Future future=getInvocationService().invokeOnRandomTarget(req);
    Object result=future.get();
    return toObject(result);
  }
 catch (  Exception e) {
    throw ExceptionUtil.rethrow(e);
  }
}
