{
  try {
    final Future future=new ClientInvocation(getClient(),req).invoke();
    Object result=future.get();
    return toObject(result);
  }
 catch (  Exception e) {
    throw ExceptionUtil.rethrow(e);
  }
}
