{
  try {
    return (Integer)invoke(new AvailableOperation(name));
  }
 catch (  Throwable t) {
    throw ExceptionUtil.rethrow(t);
  }
}
