{
  try {
    invoke();
  }
 catch (  Throwable e) {
    onException(e);
  }
}
