{
  final ICompletableFuture<V> f=removeAsyncInternal(key,null,false,true,true);
  try {
    return toObject(f.get());
  }
 catch (  Throwable e) {
    throw ExceptionUtil.rethrowAllowedTypeFirst(e,CacheException.class);
  }
}
