{
  Throwable cause=getCause(e);
  if (cause instanceof TargetNotMemberException) {
    logger.warning("Member left while recovering: " + cause);
  }
 else {
    throw ExceptionUtil.rethrow(e);
  }
}
