{
  ExecutionCallback callback=mock(ExecutionCallback.class);
  delegateThrowException=true;
  delegateFuture.run();
  outerFuture.andThen(callback);
  try {
    outerFuture.get();
    fail();
  }
 catch (  Throwable t) {
    assertEquals("Exception in execution",t.getCause().getMessage());
  }
  verifyZeroInteractions(callback);
}
